spring:
  application:
    name: newTechnologiesTesting
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:test_db
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

server:
  port: 9090

