spring:
  application:
    name: newTechnologiesTesting

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true

server:
  port: 9090



